const hofNorm=(name,tag)=>`${name||""}#${tag||""}`.replace(/\s/g,"").toLowerCase();
const hofEsc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const hofSum=(games,key)=>games.reduce((total,item)=>total+(Number(item.mp[key])||0),0);

async function renderServerHallOfFame(){
  try{
    const [stateResponse,matchesResponse]=await Promise.all([fetch("/api/app-state",{cache:"no-store"}),fetch("/api/internal-matches",{cache:"no-store"})]);
    const state=await stateResponse.json(),matches=await matchesResponse.json(),players=(state.players||[]).filter(player=>!player.archived);
    const findPlayer=mp=>players.find(player=>(player.playAliases||[]).some(alias=>alias.puuid===mp.puuid||hofNorm(alias.gameName,alias.tagLine)===hofNorm(mp.gameName,mp.tagLine)))||players.find(player=>player.puuid===mp.puuid)||players.find(player=>hofNorm(player.name,String(player.tag||"").replace(/^#/,""))===hofNorm(mp.gameName,mp.tagLine));
    const grouped=new Map(players.map(player=>[String(player.id),{player,games:[]}]))
    for(const match of matches)for(const mp of match.participants||[]){const player=findPlayer(mp);if(player)grouped.get(String(player.id))?.games.push({mp,match})}
    const rows=[...grouped.values()].map(({player,games})=>{const metricGames=games.filter(({mp})=>["objectiveDamage","damageTaken","mitigated","ccTime","wardsPlaced","wardsKilled","turretDamage"].some(key=>Number(mp[key])>0)),count=metricGames.length,seconds=metricGames.reduce((total,item)=>total+(Number(item.match.duration)||0),0),minutes=Math.max(1,seconds/60),deaths=hofSum(metricGames,"deaths"),utility=metricGames.reduce((total,{mp})=>total+(Number(mp.healsOnTeammates)||0)+(Number(mp.shieldsOnTeammates)||0)+(Number(mp.unitsHealed)>1?Number(mp.healing)||0:0),0);return {id:player.id,name:player.name,color:player.color||"#45658b",role:player.role,metricGames:count,objective:count?(hofSum(metricGames,"objectiveDamage")*.5+hofSum(metricGames,"turretDamage")*.3+(hofSum(metricGames,"turretKills")+hofSum(metricGames,"inhibitorKills"))*200)/count:0,steal:hofSum(metricGames,"objectivesStolen")+hofSum(metricGames,"objectivesStolenAssists")*.5,wall:count?(hofSum(metricGames,"damageTaken")+hofSum(metricGames,"mitigated")*.7)/minutes*Math.max(.55,1.15-deaths/count/20):0,vision:count?(hofSum(metricGames,"vision")+hofSum(metricGames,"wardsKilled")*5+hofSum(metricGames,"controlWards")*3)/minutes:0,support:count?utility/minutes:0,cc:count?(hofSum(metricGames,"ccTime")+hofSum(metricGames,"totalCcTime")*.25)/minutes:0,efficiency:count?hofSum(metricGames,"damage")/Math.max(1,hofSum(metricGames,"gold"))*1000:0,demolition:count?(hofSum(metricGames,"turretDamage")+hofSum(metricGames,"turretKills")*1500)/count:0}}),eligible=rows.filter(row=>row.metricGames>=5),roleKo={TOP:"탑",JUNGLE:"정글",MID:"미드",ADC:"원딜",SUPPORT:"서폿"},definitions=[["objectiveLeaderboard","objective",v=>Math.round(v).toLocaleString()],["stealLeaderboard","steal",v=>`${v.toFixed(1)}회`],["wallLeaderboard","wall",v=>Math.round(v).toLocaleString()],["visionLeaderboard","vision",v=>v.toFixed(1)],["supportLeaderboard","support",v=>Math.round(v).toLocaleString()],["ccLeaderboard","cc",v=>`${v.toFixed(1)}초`],["efficiencyLeaderboard","efficiency",v=>Math.round(v).toLocaleString()],["demolitionLeaderboard","demolition",v=>Math.round(v).toLocaleString()]];
    for(const [id,metric,format] of definitions){const list=eligible.filter(row=>row[metric]>0).sort((a,b)=>b[metric]-a[metric]||b.metricGames-a.metricGames).slice(0,5),element=document.querySelector(`#${id} .leaderboard-list`);if(!element)continue;element.innerHTML=list.length?list.map((row,index)=>`<button class="leaderboard-row rank-${index+1}" data-leader-player="${row.id}"><b class="leaderboard-rank">${index+1}</b><span class="avatar" style="--avatar:${hofEsc(row.color)}">${hofEsc(row.name.slice(0,1))}</span><span class="leaderboard-name"><strong>${hofEsc(row.name)}</strong><small>${hofEsc(roleKo[row.role]||row.role||"")} · 확장 ${row.metricGames}경기</small></span><em>${format(row[metric])}</em></button>`).join(""):'<div class="leaderboard-empty">현재 기준을 충족한 기록이 없습니다.</div>'}
    const summary=document.getElementById("leaderboardSummary");if(summary&&!summary.querySelector("[data-hof-count]"))summary.insertAdjacentHTML("beforeend",`<span data-hof-count>명예의전당 표본 <b>${eligible.length}명</b></span>`);
  }catch(error){console.warn("명예의전당 서버 집계 실패:",error.message)}
}
window.addEventListener("DOMContentLoaded",()=>setTimeout(renderServerHallOfFame,1400));
