import test from 'node:test';
import assert from 'node:assert/strict';
import '../rating-engine.js';
import {buildStyleProfiles,styleFeatures,percentile} from '../player-style.js';
import {radarMarkup} from '../player-radar.js';
const E=globalThis.CKRating;
function fixture(){
 const players=Array.from({length:30},(_,i)=>({id:i+1,name:'P'+i,tag:'KR1',puuid:'u'+i,tier:'GOLD',role:E.ROLES[i%5]})),matches=[];
 for(let round=0;round<3;round++)for(let group=0;group<3;group++)matches.push({gameId:String(1000+round*3+group),gameCreation:Date.UTC(2026,8,20+round),duration:1800,participants:players.slice(group*10,group*10+10).map((p,i)=>({puuid:p.puuid,gameName:p.name,tagLine:p.tag,role:p.role,roleSource:'manual',teamId:i<5?100:200,championKey:'Test',kills:3,deaths:3,assists:5,gold:10000+p.id*50,cs:100+p.id,damage:15000+p.id*200,vision:p.id,ccTime:p.id}))});
 return {players,matches};
}
test('style ranks use real confirmed role data, each player equally',()=>{const {players,matches}=fixture(),copy=structuredClone({players,matches}),profiles=buildStyleProfiles(players,matches,{},E),p=profiles.get(1,'TOP');assert.equal(p.games,3);assert.equal(p.sessions,3);assert.equal(p.available,6);assert.ok(p.metrics.every(m=>m.peers===6&&m.index>=0&&m.index<=100));assert.ok(p.metrics[0].index<profiles.get(26,'TOP').metrics[0].index);assert.deepEqual({players,matches},copy);});
test('ties have the same midpoint percentile, not random ranks',()=>{assert.equal(percentile(2,[2,2,2,2,2]),50);assert.equal(percentile(0,[0,1,2,3,4]),10);assert.equal(percentile(4,[0,1,2,3,4]),90);});
test('same-series repetition does not change the session-weighted style',()=>{const {players,matches}=fixture(),before=buildStyleProfiles(players,matches,{},E).get(1,'TOP');for(let i=0;i<4;i++)matches.push({...structuredClone(matches[0]),gameId:String(2000+i),gameCreation:matches[0].gameCreation+i*60000});const after=buildStyleProfiles(players,matches,{},E).get(1,'TOP');assert.equal(after.sessions,3);assert.equal(after.games,7);assert.deepEqual(after.metrics.map(m=>m.index),before.metrics.map(m=>m.index));});
test('duplicate matches are not counted twice',()=>{const {players,matches}=fixture();matches.push(structuredClone(matches[0]));assert.equal(buildStyleProfiles(players,matches,{},E).get(1,'TOP').games,3);});
test('missing, too few games, and too few peers are distinct, never zero',()=>{const {players,matches}=fixture();for(const m of matches)for(const p of m.participants)if(p.puuid==='u0')p.ccTime=null;const profiles=buildStyleProfiles(players,matches,{},E);assert.equal(profiles.get(1,'TOP').metrics[5].reason,'missing');assert.equal(profiles.get(1,'TOP').metrics[5].index,null);assert.equal(profiles.get(1,'ADC').metrics[0].reason,'no-games');assert.equal(buildStyleProfiles(players,matches.slice(0,1),{},E).get(1,'TOP').metrics[0].reason,'few-games');assert.equal(buildStyleProfiles(players,matches.filter((_,i)=>i%3===0),{},E).get(1,'TOP').metrics[0].reason,'few-peers');});
test('zero CC is usable only when collection is evident; missing kills do not invent KP',()=>{const {matches}=fixture(),m=matches[0],p=m.participants[0];p.ccTime=0;assert.equal(styleFeatures(p,m).control,0);p.ccTime=null;assert.equal(styleFeatures(p,m).control,undefined);for(const x of m.participants)x.ccTime=0;assert.equal(styleFeatures(p,m).control,undefined);delete m.participants[1].kills;assert.equal(styleFeatures(p,m).fight,undefined);assert.equal(styleFeatures(p,m).survival,undefined);p.vision=-1;assert.equal(styleFeatures(p,m).vision,undefined);});
test('uncertain and duplicate role assignments are excluded',()=>{const {players,matches}=fixture();for(const m of matches)if(m.participants[0].puuid==='u0')m.participants[0].roleSource='inferred';assert.equal(buildStyleProfiles(players,matches,{},E).get(1,'TOP').games,0);});
test('incomplete radar does not fill missing axes as zero',()=>{const svg=radarMarkup({width:240,labels:['a','b','c','d','e','f'],values:[0,30,null,50,70,90],max:100,style:true});assert.ok(!svg.includes('class="radar-area"'));assert.ok(svg.includes('class="radar-segment"'));assert.ok(svg.includes('>—</text>'));assert.ok(!/NaN|undefined/.test(svg));const empty=radarMarkup({width:240,labels:['a','b','c'],values:[null,null,null],max:100,style:true});assert.ok(empty.includes('관측 없음'));assert.ok(!empty.includes('class="radar-point'));});
