import test from 'node:test';
import assert from 'node:assert/strict';
import {assertNoUntrackedSeriesManagement,seriesCopies,validateSeriesRoles} from '../series-management.mjs';

const roles=['TOP','JUNGLE','MID','ADC','SUPPORT'];
const series=()=>({id:1,seriesNumber:'CKS-20260921-001',blue:roles.map((role,index)=>({id:index+1,role})),red:roles.map((role,index)=>({id:index+6,role})),sets:[{number:1,gameId:'100',imported:true},{number:2,gameId:'',imported:false}]});
const state=()=>({active:series(),history:[],deletedSeriesNumbers:[]});
test('validates exactly one of each role per team',()=>{const source=series(),overrides=Object.fromEntries([...source.blue,...source.red].map(member=>[String(member.id),member.role]));overrides[4]='SUPPORT';overrides[5]='ADC';assert.equal(validateSeriesRoles(source,overrides)['4'],'SUPPORT');assert.throws(()=>validateSeriesRoles(source,{...overrides,5:'SUPPORT'}));assert.throws(()=>validateSeriesRoles(source,{...overrides,11:'MID'}))});
test('ordinary set import and finish stay available but unaudited edits and deletion are rejected',()=>{const old=state(),added=structuredClone(old);added.active.sets[1]={number:2,gameId:'200',winner:'BLUE',imported:true};assert.doesNotThrow(()=>assertNoUntrackedSeriesManagement(old,added));const edited=structuredClone(old);edited.active.sets[0].roleOverrides={'4':'SUPPORT','5':'ADC'};assert.throws(()=>assertNoUntrackedSeriesManagement(old,edited),{status:403});const addedOverride=structuredClone(old);addedOverride.active.sets.push({number:3,roleOverrides:{4:'SUPPORT'}});assert.throws(()=>assertNoUntrackedSeriesManagement(old,addedOverride),{status:403});const movedTeam=structuredClone(old);[movedTeam.active.blue[0],movedTeam.active.red[0]]=[movedTeam.active.red[0],movedTeam.active.blue[0]];assert.throws(()=>assertNoUntrackedSeriesManagement(old,movedTeam),{status:403});const deleted=structuredClone(old);deleted.active=null;assert.throws(()=>assertNoUntrackedSeriesManagement(old,deleted),{status:403});const resurrected=structuredClone(old);resurrected.deletedSeriesNumbers=[old.active.seriesNumber];assert.throws(()=>assertNoUntrackedSeriesManagement(resurrected,old),{status:409})});
test('series lookup returns active and history copies for one ID',()=>{const item=series(),source={active:item,history:[structuredClone(item)]};assert.equal(seriesCopies(source,1).length,2);assert.equal(seriesCopies(source,item.seriesNumber).length,2)});
